const siteKeywords = [

    // ── Ministry & Government ─────────────────────────────────────────────────
    'Imo State',
    'Imo State Government',
    'Imo State Ministry of Education',
    'Imo State Ministry of Primary and Secondary Education',
    'Ministry of Education Nigeria',
    'Imo Education',
    'Owerri',
    'Southeast Nigeria Education',
    'Imo State Civil Service',
    'Nigerian Government Portal',
    'Government Education Portal Nigeria',
    'Federal Ministry of Education Nigeria',
    'Universal Basic Education Commission',
    'UBEC Nigeria',
    'State Universal Basic Education Board',
    'SUBEB Imo',
    'Imo SUBEB',

    // ── Education Levels & Institutions ──────────────────────────────────────
    'Primary Education Nigeria',
    'Secondary Education Nigeria',
    'Basic Education Nigeria',
    'Junior Secondary School',
    'JSS Results',
    'Public School Imo State',
    'Government School Nigeria',
    'Primary School Imo State',
    'Secondary School Imo State',
    'Junior Secondary School Imo',
    'Senior Secondary School Imo',
    'JSS1 JSS2 JSS3 Results',
    'Nigeria Basic Education',
    'Universal Basic Education Nigeria',
    'Free Education Nigeria',
    'School System Nigeria',

    // ── Examinations ─────────────────────────────────────────────────────────
    'BECE',
    'Basic Education Certificate Examination',
    'BECE Results',
    'BECE Results 2024',
    'BECE Results 2025',
    'BECE Imo State',
    'BECE Nigeria',
    'Check BECE Result',
    'BECE Exam Number',
    'UBEAT',
    'Universal Basic Education Assessment Test',
    'UBEAT Results',
    'UBEAT Results 2024',
    'UBEAT Results 2025',
    'UBEAT Imo State',
    'UBEAT Nigeria',
    'Check UBEAT Result',
    'UBEAT Exam Number',
    'Imo State Exam Results',
    'Check Exam Results Nigeria',
    'Nigeria Exam Results Online',
    'Imo State Examination Board',
    'JSS Exam Results Nigeria',

    // ── Student Portal ────────────────────────────────────────────────────────
    'Student Portal',
    'Student Portal Imo State',
    'Check Results Online',
    'Exam Results Portal',
    'Nigeria Student Results',
    'View My Results',
    'Exam Number Results',
    'Student Results Checker',
    'Online Results Checker Nigeria',
    'Check My Exam Result',
    'Student Dashboard Nigeria',
    'Result Checking Portal Nigeria',
    'Student Login Nigeria',
    'Academic Results Nigeria',
    'School Results Portal Nigeria',

    // ── Parents & Guardians ───────────────────────────────────────────────────
    'Check Child Exam Result Nigeria',
    'Ward Results Nigeria',
    'Primary School Result Nigeria',
    'Junior WAEC Imo State',
    'How to Check BECE Result',
    'How to Check UBEAT Result',

    // ── School Onboarding / AEE ───────────────────────────────────────────────
    'School Registration Imo State',
    'AEE Portal',
    'Authorised Education Enumerator',
    'Student Onboarding Nigeria',
    'School Enrollment Imo',
    'School Enrollment Nigeria',
    'AEE Registration',
    'Education Enumerator Nigeria',
    'Student Registration Portal Nigeria',
    'School Data Capture Nigeria',
    'Exam Registration Nigeria',
    'Student Biometric Registration Nigeria',

    // ── Built by Imo Digital City ─────────────────────────────────────────────
    'Imo Digital City',
    'Imo Digital City Nigeria',
    'Imo Digital City Tech',
    'Software Company Imo State',
    'Tech Company Imo State',
    'Nigerian Software Company',
    'Government Software Nigeria',
    'Imo Tech',
    'Nigeria GovTech',
    'EdTech Nigeria',
    'Digital Transformation Nigeria',
    'GovTech Imo State',
    'Smart Government Nigeria',
    'Digital Education Nigeria',
    'Nigeria Education Technology',
    'Public Sector Software Nigeria',
    'eGovernment Nigeria',

]

export default siteKeywords